language: c

sudo: false

env:
  global:
    - CC=$CC
    - CROSS_COMPILE=""
    - CONFIGURE_ARGS=""
    - CFLAGS=-Iinstall/lua/include
    - LDFLAGS=-Linstall/lua/lib
    - OSX=x

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - env: CONFIGURE_ARGS="--cross-compile=i586-mingw32msvc- --cross-execute=wine --platform=win32 --mingw=/usr/i586-mingw32msvc"
      os: linux
      compiler: gcc
    - env: OSX=10.10
      os: osx
      osx_image: xcode7.1
      compiler: clang
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.2
      compiler: clang

addons:
  apt:
    packages:
      - libtalloc-dev
      - mingw32
      - mingw32-runtime
      - python-jinja2
      - wine

cache: apt

before_install:
  - echo "OSX=$OSX"
  - if [ "$OSX" != "x" ]; then brew update; fi
  - if [ "$OSX" != "x" ]; then brew install python talloc; fi
  - if [ "$OSX" != "x" ]; then pip install --upgrade pip; fi
  - if [ "$OSX" != "x" ]; then pip install Jinja2; fi

script:
  - ./configure $CONFIGURE_ARGS
  - cat wright.log
  - cat Makefile
  - make V=1
